### ISSUE TITLE
.DS_Store

### ISSUE THREAD

**Issue by kqnade** [Q0tzly/HTML-ONLY#2]
.DS_Storeファイルは不要ファイルだから,gitignoreしたほうがいいっぴよ

**Comment by DevPeople955** [comment]
> . DS_Storeファイルは不要ファイルだから,gitignoreしたほうがいいっぴよ

DS_Storeファイルって何に使うやつ？

**Comment by kqnade** [comment]
ファイルキャッシュだった希ガス()

**Comment by Q0tzly** [comment]
Delete “.DS_Store”

**Comment by kqnade** [comment]
imgディレクトリ内に残っとるよ〜
